const REQUEST_CARDS: string = 'REQUEST_CARDS';
const REQUEST_CARDS_SUCCESS: string = 'REQUEST_CARDS_SUCCESS';
const REQUEST_CARDS_FAILURE: string = 'REQUEST_CARDS_FAILURE';
const TOGGLE_STATUS: string = 'TOGGLE_STATUS';

export {
    REQUEST_CARDS,
    REQUEST_CARDS_SUCCESS,
    REQUEST_CARDS_FAILURE,
    TOGGLE_STATUS,
}